### ISSUE TITLE
Group Project Kanban Board Setup

### ISSUE THREAD

**Issue by pushkar1995** [pushkar1995/space-travelers-hub#121]
Project URL: https://github.com/pushkar1995/space-travelers-hub/projects/1
Note for the Reviewer:
This issue is created for the Review Purpose by the Reviewer of the Kanban Board designed for the Group Project done by 2 team members group. @BilalLiaquat7 (
Muhammad Bilal Liaquat) &  @pushkar1995 (Pushkar Gautam)

**Comment by addod19** [comment]
## Hi @pushkar1995 and @BilalLiaquat7, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Information about the number of people and link to kanban board provided :100: 
- [ ] All tasks have title and description assigned to user :rocket: 
- [ ] Points are distributed in a fair manner :fireworks: 
- [ ] The number of cards in the backlog is equal to 17 :rocket: 
- [ ] All categories present :1st_place_medal: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
